eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8086
spring:
  application:
    name: netflix-hystrix-turbine
turbine:
  app-config: limits-service, currency-exchange-service, currency-conversion-service
  clusterNameExpression: new String("default")

  # aggregator:
  #   cluster-config:
  #   - LIMITS-SERVICE
  #   - CURRENCY-EXCHANGE-SERVICE
  #   - CURRENCY-CONVERSION-SERVICE

