server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunoluizdesiqueira/conversor-moedas-configs.git
  rabbitmq:
    password: melhorsenhadomundo
    username: rabbit666   
